name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr-checks:
    uses: progami/shared-workflows/.github/workflows/pr-checks.yml@main
    with:
      check-pr-title: true
      add-size-labels: true
      comment-test-results: false
      size-thresholds: |
        {
          "xs": 10,
          "s": 100,
          "m": 500,
          "l": 1000
        }
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
